spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sql-db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update