jasypt:
  encryptor:
    password: projectopenchef
server:
  port: 8082
  servlet:
    context-path: ${ORDERS_CONTEXT_PATH:/airchef/v1}
  compression:
    enabled: true
    mime-types: application/json,text/html,text/xml,text/plain,text/css,text/javascript

spring:
  application:
    name: chef-order-service
  main:
    banner-mode: "off"
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas:
      location: classpath:db/db.migration
  datasource:
    #    url: jdbc:postgresql://localhost:26257/foodiodb?sslmode=verify-full&applciation_name=transationservice&logServerErrorDetail=falsesocketTimeout=30
    url: jdbc:postgresql://localhost:26258/chef_db?logServerErrorDetail=false&socketTimeout=30
    username: chef_db_user
    password:
      driver-class-name: org.postgresql.Driver
    hikari:
      autocommit: true
      poolName: CockroachHikariCP
      minimumIdle: 5
      validation-timeout: 500
      conenctionTimeout: 5000
      maximum-pool-size: 20
      keepalive-time: 60000
      max-lifetime: 240000
    jpa:
      properties:
        hibernate:
          order_inserts: true
          order_updates: true
          dialect: org.hibernate.dialect.PostgreSQL95Dialect
          use_sql_comments: true
          format_sql: true
          jdbc:
            batch_size: 20
            batch_versioned_data: true
            lob:
              non_contextual_creation: true
      show-sql: false
      open-in-view: false


  logging:
    level:
      root: INFO
    org:
      springframework.web: INFO
      hibernate: INFO
      hibernate.SQL: INFO
      hibernate.cache: INFO
      hibernate.stat: INFO


  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username:
    pasword:
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

smtp:
  server: ${SMTP_SERVER:smtp.gmail.com}
  username: ENC(LkDbZfYefONZr/c5TX4NH0pJG9D355M49WaudG4Ivx1NQKAU1lIqiQ==)
  password: ENC(TjG6Eql70rAePtLrGyax+lC+FaRoZ7rx)
  debug: false


management:
  info:
    defaults:
      enabled: false
  endpoints:
    web:
      base-path: '/'
      exposure:
        include: metrics,health,refresh,info
  endpoint:
    info:
      enabled: true
    metrics:
      enabled: true
    refresh:
      enabled: true
    prometheus:
      enabled: true

stripe:
  private:
    key: ${STRIPE_SECRET_KEY:sk_test_51KRx9YHvD8eQSoOrtSOiY7SvoZe4Zy64LC6SJCwegu2e5hywt0VuN9pdSEgMOQubt0wUlGd9LlkcierZjcVgBsL4005ZiH1Cig}
  success:
    url: ${STRIPE_SUCCESS_URL:http://localhost:4200/checkout/success}
  cancel:
    url: ${STRIPE_CANCEL_URL:http://localhost:4200/checkout/failure}
  currency: ${STRIPE_CURRENCY:gbp}



